ALTER TABLE backup_records
  ADD COLUMN storage_format varchar(10) NOT NULL DEFAULT 'full',
  ADD COLUMN parent_id uuid,
  ADD COLUMN version_sequence bigint GENERATED BY DEFAULT AS IDENTITY,
  ADD CONSTRAINT backup_records_storage_format_check CHECK (
    (storage_format = 'full' AND parent_id IS NULL)
    OR (storage_format = 'delta' AND parent_id IS NOT NULL AND parent_id <> id)
  ),
  ADD CONSTRAINT backup_records_parent_target UNIQUE (id, project_id, provider),
  ADD CONSTRAINT backup_records_parent_fk FOREIGN KEY (parent_id, project_id, provider)
    REFERENCES backup_records (id, project_id, provider) DEFERRABLE INITIALLY DEFERRED;

-- Preserve the chronological order of existing full archives during migration.
WITH ordered AS (
  SELECT id, row_number() OVER (ORDER BY created_at, id) AS position FROM backup_records
)
UPDATE backup_records SET version_sequence = ordered.position FROM ordered WHERE backup_records.id = ordered.id;
SELECT setval(pg_get_serial_sequence('backup_records', 'version_sequence'),
  COALESCE((SELECT max(version_sequence) FROM backup_records), 1),
  EXISTS (SELECT 1 FROM backup_records));

CREATE INDEX backup_records_parent_idx ON backup_records(parent_id);
CREATE INDEX backup_records_version_idx ON backup_records(project_id, provider, version_sequence DESC);

-- Drive files are removed only after the database has committed a safe history.
-- Failed remote deletions remain queued for the scheduler to retry.
CREATE TABLE backup_remote_deletions (
  provider_file_id text PRIMARY KEY,
  user_id uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  created_at timestamptz NOT NULL DEFAULT now()
);
